### PR TITLE
fix blog page to show 1 blog

### LINKED ISSUE #100: fix blog page to show 1 blog
**Expected behavior:**only 1 blog shoul open

**Actual behavior:**
image

### PR DESCRIPTION
**Pull request by batoulst**
# Description
fix blog page to show 1 blog

## Related Issue

Fixes #100 

## Screenshots

image
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally
- [ ] Added tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I've run linter, prettier, and removed all `console.log`
- [x] I've reverted all the files back that are not related to the issue (App.js, index.js, ...)

### CODE REVIEW

File: src/pages/Blogs/BlogCard.jsx [hunk 1]
```diff
@@ -5,11 +5,15 @@ import { useSelector } from 'react-redux';
 import { selectUser } from '../../features/users/usersSlice';
 
 function BlogCard({ blog }) {
+  const handleClick=()=>{
+    
+    navigate('/blogs/blog', {state:{blog: blog}})
```
Comment (chiturca) [inline src/pages/Blogs/BlogCard.jsx:10]: Oh I never knew we can write navigate like this, such a good solution!

**Review by chiturca — APPROVED** [review]
I admire how clean you write your code!
Thanks a lot! 💜

**Review by ahmadmhd357 — APPROVED** [review]
amazing thank you
